# Generated by Django 6.0.4 on 2026-04-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantech', '0003_pedido_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('LIVRE', 'Livre'), ('OCUPADA', 'Ocupada'), ('CONTA', 'Aguardando Conta'), ('PAGO', 'Pago')], default='LIVRE', max_length=10),
        ),
    ]
