# Generated by Django 6.0.4 on 2026-04-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantech', '0004_alter_mesa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('RECEBIDO', 'Recebido'), ('PREPARANDO', 'Em Preparação'), ('PRONTO', 'Pronto para Entrega'), ('ENTREGUE', 'Entregue'), ('PAGO', 'Pago')], default='RECEBIDO', max_length=15),
        ),
    ]
